### ISSUE TITLE
Heroku build error

### ISSUE THREAD

**Issue by Evert-jvv** [wojtekmach/acme_bank#18]
Getting this error when trying to deploy to heroku (using the quick deploy option on the repo):

```
[33mwarning: [0mvariable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/scrivener_ecto/mix.exs:10

[33mwarning: [0mvariable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/scrivener_ecto/mix.exs:12

[33mwarning: [0mvariable "aliases" does not exist and is being expanded to "aliases()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/scrivener_ecto/mix.exs:13

[33mwarning: [0mvariable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/ex_admin/mix.exs:16

[33mwarning: [0mvariable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/ex_admin/mix.exs:17

[33mwarning: [0mvariable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/ex_queb/mix.exs:13

[33mwarning: [0mvariable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /app/deps/ex_queb/mix.exs:15

[31m
15:58:27.684 [error] GenServer #PID<0.255.0> terminating
** (ArgumentError) argument error
    (postgrex) lib/postgrex/utils.ex:38: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:38: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.bootstrap_send/4
    (postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
State: Postgrex.Protocol
[0m[31m
15:58:27.698 [error] GenServer #PID<0.262.0> terminating
** (ArgumentError) argument error
    (postgrex) lib/postgrex/utils.ex:38: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:38: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.bootstrap_send/4
    (postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
State: Postgrex.Protocol
[0m** (exit) exited in: :gen_server.call(#PID<0.255.0>, {:checkout, #Reference<0.0.6.1820>, true, :infinity}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (postgrex) lib/postgrex/utils.ex:38: anonymous fn/1 in Postgrex.Utils.parse_version/1
            (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
            (postgrex) lib/postgrex/utils.ex:38: Postgrex.Utils.parse_version/1
            (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.bootstrap_send/4
            (postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
            (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
            (connection) lib/connection.ex:622: Connection.enter_connect/5
    (db_connection) lib/db_connection/poolboy.ex:112: DBConnection.Poolboy.checkout/3
    (db_connection) lib/db_connection.ex:712: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:619: DBConnection.run/3
    (db_connection) lib/db_connection.ex:921: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:91: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:185: Ecto.Adapters.SQL.query!/5
```

**Comment by wojtekmach** [comment]
I think this can be fixed by updating Postgrex, could you give this a shot and send a PR?
